name: latest release on CLN v25.02

on:
    release:
        types: [published, edited]
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v25.02"
            pyln-version: "25.02"
            tagged-release: true