name: Latest release on CLN v25.05.x

on:
    release:
        types: [published, edited]
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v25.05"
            pyln-version: "25.5"
            tagged-release: true