name: latest release on CLN v25.05

on:
    release:
        types: [published, edited]
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v25.05rc1"
            pyln-version: "25.2.2"
            tagged-release: true