name: Latest release on CLN v25.02.x

on:
    release:
        types: [published, edited]
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v25.02.1"
            pyln-version: "25.2.1"
            tagged-release: true