name: latest release on CLN v24.11

on:
    release:
        types: [published, edited]
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v24.11"
            pyln-version: "24.11"
            tagged-release: true