name: master on CLN v25.12.x

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'tools/**'
            - 'CHANGELOG.md'
            - 'README.md'
            - 'LICENSE'
            - '.gitignore'
            - 'coffee.yml'
            - 'tests/setup.sh'
    pull_request:
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v25.12.1"
            pyln-version: "25.12.1"
            tagged-release: false
            python-version-1: "3.10"
            python-version-2: "3.12"
